"""
Run a scripted conversation against the real model and write it to
docs/example_conversations.md, the transcript quoted in the README.

    python scripts/run_demo.py

It uses the same DocumentAssistant as main.py, so it also leaves a real session file in
sessions/ and a real tool-call log in logs/. The second half restarts the assistant and
resumes the session, to show memory surviving a restart.
"""
import json
import os
import sys
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")

from dotenv import load_dotenv  # noqa: E402

load_dotenv(os.path.join(ROOT, ".env"))

from assistant import DocumentAssistant  # noqa: E402

CONVERSATION = [
    ("Q&A with a source citation", "What's the total amount due on invoice INV-002?"),
    ("Q&A over a filtered search", "Find documents with amounts over $50,000"),
    ("Calculation across documents", "Calculate the sum of all invoice totals"),
    ("Calculation, follow-up resolved from memory", "What is the average of those?"),
    ("Summarization", "Summarize the service agreement"),
    ("Calculation, follow-up on the summarized document", "What would it cost if it ran for 18 months instead?"),
    ("Summarization of a healthcare document", "Give me the key points of the insurance claim"),
    ("Unknown intent, routed to the Q&A default", "Hi! What can you do?"),
]
AFTER_RESTART = [
    ("Memory after a restart", "Remind me which claim we just looked at, and who the claimant is."),
]


def make_assistant() -> DocumentAssistant:
    return DocumentAssistant(
        openai_api_key=os.environ["OPENAI_API_KEY"],
        model_name=os.getenv("MODEL_NAME", "gpt-4o"),
        temperature=float(os.getenv("TEMPERATURE", "0.1")),
    )


def render_turn(n: int, title: str, text: str, r: dict) -> str:
    if not r["success"]:
        return f"### {n}. {title}\n\n**User:** {text}\n\n**Error:** {r['error']}\n"
    intent = r["intent"] or {}
    out = [f"### {n}. {title}", "", f"**User:** {text}", "", "**Assistant:**", ""]
    out += ["> " + line if line else ">" for line in (r["response"] or "").splitlines()]
    out += [
        "",
        "| | |", "|---|---|",
        f"| Intent | `{intent.get('intent_type')}` (confidence {intent.get('confidence', 0):.2f}) |",
        f"| Reasoning | {intent.get('reasoning', '').replace('|', '/')} |",
        f"| Graph path | `{' -> '.join(r['actions_taken'])}` |",
        f"| Tools used | {', '.join(f'`{t}`' for t in r['tools_used']) or 'none'} |",
        f"| Active documents | {', '.join(r['active_documents']) or 'none'} |",
        f"| Memory summary | {r['summary'].replace('|', '/')} |",
        "",
        "<details><summary>Structured response (Pydantic)</summary>",
        "",
        "```json",
        json.dumps(r["structured_response"], indent=2, ensure_ascii=False),
        "```",
        "</details>",
        "",
    ]
    return "\n".join(out)


def main():
    a = make_assistant()
    sid = a.start_session("demo_user")
    parts = [
        "# Example conversations",
        "",
        f"Generated by `scripts/run_demo.py` on {datetime.now():%Y-%m-%d %H:%M} with "
        f"`{os.getenv('MODEL_NAME', 'gpt-4o')}`. This is real model output, not hand-written. "
        f"Session `{sid}`: its session file is `sessions/{sid}.json` and its tool log is "
        f"`logs/session_{sid}.json`.",
        "",
    ]
    n = 0
    for title, text in CONVERSATION:
        n += 1
        print(f"[{n}] {text}")
        parts.append(render_turn(n, title, text, a.process_message(text)))

    # A new assistant is a new process as far as memory goes: a fresh InMemorySaver.
    parts += ["---", "",
              "**Restart.** A brand-new `DocumentAssistant` (with an empty `InMemorySaver`) resumes "
              f"session `{sid}` from `sessions/{sid}.json`.", ""]
    b = make_assistant()
    b.start_session("demo_user", sid)
    for title, text in AFTER_RESTART:
        n += 1
        print(f"[{n}] {text}")
        parts.append(render_turn(n, title, text, b.process_message(text)))

    path = os.path.join(ROOT, "docs", "example_conversations.md")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(parts))
    print(f"Wrote {path}")


if __name__ == "__main__":
    main()
